plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.NeuroIndex'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

ext {
    set('springAiVersion', "1.0.0")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

repositories {
	mavenCentral()
    mavenLocal()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.NeuroIndex:entity:0.0.3-SNAPSHOT'
    implementation 'org.springframework.ai:spring-ai-starter-model-ollama'
    implementation 'com.pgvector:pgvector:0.1.6'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
    // Source: https://mvnrepository.com/artifact/org.apache.lucene/lucene-core
    implementation("org.apache.lucene:lucene-core:10.4.0")
    // Source: https://mvnrepository.com/artifact/org.apache.lucene/lucene-queryparser
    implementation("org.apache.lucene:lucene-queryparser:10.4.0")
    implementation 'org.apache.opennlp:opennlp-tools:2.5.5'
    // Source: https://mvnrepository.com/artifact/redis.clients/jedis
    implementation("redis.clients:jedis:7.5.2")
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
//	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
